### ISSUE TITLE
Adding dot, line or custom leaders

### ISSUE THREAD

**Issue by jeroenkruis** [mauvm/documark-table-of-contents#7]
As seen on [w3.org](http://www.w3.org/Style/Examples/007/leaders). I've implemented my own way of doing this by using css' `content` attribute and the `:after` selector. Since the last update it broke my css that made this possible.

I used to do something like this.

``` css
chapter table-of-contents ul .index-2 > li:after {
    float: left;
    width: 0;
    white-space: nowrap;
    content: " . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ";
}
```

**Comment by mauvm** [comment]
Is the space between `ul` and `.index-2` intentional?

The elements no longer float, since this caused an issue with rendering. They have relative and absolute positioning now. Also see https://github.com/documark/dmp-style-basic/blob/master/src/style.styl#L109.

Please let me know if this works:

``` css
chapter table-of-contents ul li span.chapter-title {
    width: auto;
    padding-right: 20px;
    background-color: white;
}
chapter table-of-contents ul li:before {
    float: left;
    width: 0;
    white-space: nowrap;
    content: " . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ";
}
```

Also it might be better to use a background image, since the dots are now selectable and will be there when the table of contents is copy/pasted.

**Comment by jeroenkruis** [comment]
You're right the space was not needed after all. It really depends on what you want to achieve. I want to achieve dot leaders that apply only on the sub chapters, not on the main chapters. I've edited your code and it works like a charm.

``` css
chapter table-of-contents ul li span.chapter-title {
    width: auto;
    padding-right: 6px;
    background-color: white;
}

chapter table-of-contents ul li span.page-number {
    padding-top: 7px;
}

chapter table-of-contents ul.index-2 > li:before {
    float: left;
    width: 0;
    white-space: nowrap;
    content: " . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ";
}

```

![screen shot 2015-05-21 at 09 42 14](https://cloud.githubusercontent.com/assets/1212674/7743730/be9109fa-ff9d-11e4-8652-709e8aaec493.png)
